//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_ACCOUNT
    {
        public string A_USERNAME { get; set; }
        public decimal ADMIN_ID { get; set; }
        public string A_PASSWORD { get; set; }
        public string A_EMAIL { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ADMIN ADMIN1 { get; set; }
    }
}
