//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.CLIENT_ACCOUNT = new HashSet<CLIENT_ACCOUNT>();
            this.CLIENT_ACCOUNT1 = new HashSet<CLIENT_ACCOUNT>();
            this.RENTs = new HashSet<RENT>();
            this.SEARCHBYCRITERIAs = new HashSet<SEARCHBYCRITERIA>();
            this.GAMEs = new HashSet<GAME>();
            this.GAMEs1 = new HashSet<GAME>();
        }
    
        public decimal CLIENT_ID { get; set; }
        public string C_FIRSTNAME { get; set; }
        public string C_LASTNAME { get; set; }
        public decimal C_AGE { get; set; }
        public string C_PNUM { get; set; }
        public string C_CITY { get; set; }
        public string C_GOV { get; set; }
        public string C_STREET { get; set; }
        public string GENDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_ACCOUNT> CLIENT_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_ACCOUNT> CLIENT_ACCOUNT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENT> RENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEARCHBYCRITERIA> SEARCHBYCRITERIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME> GAMEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME> GAMEs1 { get; set; }
    }
}
