//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_ACCOUNT
    {
        public string C_USERNAME { get; set; }
        public decimal CLIENT_ID { get; set; }
        public string C_PASSWORD { get; set; }
        public string C_EMAIL { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual CLIENT CLIENT1 { get; set; }
    }
}
