//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GAME()
        {
            this.GAME_CATEGORIES = new HashSet<GAME_CATEGORIES>();
            this.GAME_PLATFORMS = new HashSet<GAME_PLATFORMS>();
            this.RENTs = new HashSet<RENT>();
            this.SEARCHBYCRITERIAs = new HashSet<SEARCHBYCRITERIA>();
            this.UPDATEGAMEDETAILS = new HashSet<UPDATEGAMEDETAIL>();
            this.CLIENTs = new HashSet<CLIENT>();
            this.CLIENTs1 = new HashSet<CLIENT>();
        }
    
        public decimal GAME_ID { get; set; }
        public decimal VENDOR_ID { get; set; }
        public Nullable<decimal> ADMIN_ID { get; set; }
        public string G_NAME { get; set; }
        public decimal YEAR { get; set; }
        public Nullable<System.DateTime> ADDITIONDATE { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME_CATEGORIES> GAME_CATEGORIES { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GAME_PLATFORMS> GAME_PLATFORMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENT> RENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEARCHBYCRITERIA> SEARCHBYCRITERIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UPDATEGAMEDETAIL> UPDATEGAMEDETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT> CLIENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT> CLIENTs1 { get; set; }
    }
}
