//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Games_Rental_SystemEntities1 : DbContext
    {
        public Games_Rental_SystemEntities1()
            : base("name=Games_Rental_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ADMIN_ACCOUNT> ADMIN_ACCOUNT { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CLIENT_ACCOUNT> CLIENT_ACCOUNT { get; set; }
        public virtual DbSet<GAME> GAMEs { get; set; }
        public virtual DbSet<GAME_CATEGORIES> GAME_CATEGORIES { get; set; }
        public virtual DbSet<GAME_PLATFORMS> GAME_PLATFORMS { get; set; }
        public virtual DbSet<RENT> RENTs { get; set; }
        public virtual DbSet<SEARCHBYCRITERIA> SEARCHBYCRITERIAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UPDATEGAMEDETAIL> UPDATEGAMEDETAILS { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
    }
}
