//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENT
    {
        public decimal GAME_ID { get; set; }
        public decimal CLIENT_ID { get; set; }
        public decimal VENDOR_ID { get; set; }
        public Nullable<System.DateTime> DATEOFRENTING { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual GAME GAME { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
