//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPDATEGAMEDETAIL
    {
        public decimal ADMIN_ID { get; set; }
        public decimal GAME_ID { get; set; }
        public string PLATFORM { get; set; }
        public string CATEGORY { get; set; }
        public string G_NAME { get; set; }
        public Nullable<decimal> YEAR { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual GAME GAME { get; set; }
    }
}
